apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-weather
  labels:
    app: nginx-for-svc2
  # annotations:
    # kubernetes.io/change-cause: version 1.10.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-for-svc2
  template:
    metadata:
      labels:
        app: nginx-for-svc2
    spec:
      containers:
      - name: nginx-weather
        image: rnlgud123/weather:01
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

